### ISSUE TITLE
PHP warning when configuring a new slot

### ISSUE THREAD

**Issue by centreon** [centreon/centreon-dsm#11]
---

Author Name: **Simon Bomm** (Simon Bomm)
Original Redmine Issue: 4628, https://forge.centreon.com/issues/4628
Original Date: 2013-07-15

---

Hi, 

When reaching "Administration > Modules > [Dynamic Services] -- Configure", there's a php warning showing up (cf attached files).

Error ligne 1497 of /usr/share/centreon/www/include/common/common-Func.php 

In following function, $chemintotal is pointing to an nonexistent directory, should be a translation issue. 

function getLangs(){
                $langs = array();
                $chemintotal = "./locale/";
                $default = "en_US";

                $langs["en_US"] = "en_US";
                if ($handle  = opendir($chemintotal))   {
                    while ($file = readdir($handle))
                        if (is_dir("$chemintotal/$file") && strcmp($file, ".") && strcmp($file, ".."))
                                $langs[$file] = $file;
                        closedir($handle);
                }
                return $langs;
        }

Thanks you,

**Comment by lpinsivy** [comment]
doesn't exist with Centreon web 2.7 and DSM 2.1
