### ISSUE TITLE
Error on the documentation

### ISSUE THREAD

**Issue by ddu17** [centreon/centreon-dsm#26]
Hello, 

I'm installing Centreon DSM using following documentation :

https://documentation.centreon.com/docs/centreon-dsm/en/latest/installation/from_packages.html#install-a-central-server

I'm using CES 3, the following command does not work :
`yum install centreon-dsm`

In my mind the command should be this one : 
`yum install centreon-dsm-server`

If you can confirm this feedback, the online documentation should be updated.

Best regards.

**Comment by julienmathis** [comment]
I think the doc online is not uptodate because in sources, the code is ok : https://github.com/centreon/centreon-dsm/blob/master/doc/en/installation/from_packages.rst

I will update the doc asap.
