### ISSUE TITLE
Documentation, Wiki, Explanation

### ISSUE THREAD

**Issue by centreon** [centreon/centreon-dsm#3]
---

Author Name: **Jérémie Pradet** (Jérémie Pradet)
Original Redmine Issue: 2566, https://forge.centreon.com/issues/2566
Original Date: 2011-07-18

---

Hello

Can we have a explanation, presentation and documation of DSM ? (English or French)
because I don't understand this extension.

Than you

-

**Comment by leoncx** [comment]
Duplicate #17
