### ISSUE TITLE
Variable not exported at the installation

### ISSUE THREAD

**Issue by tseegers** [centreon/centreon-dsm#40]
Hello,

When we install the packet centreon-dsm-server 2.1.2 a variable is not well exported in the file /etc/init.d/dsmd and the service refuses to start

Line 14:
#binary=@CENTREON_BINDIR@/dsmd.pl

Yet the variable is present in "/etc/centreon/instCentWeb.conf"

CENTREON_BINDIR=/usr/share/centreon/bin

If you replace manually the init file the line 14 by "/usr/share/centreon/bin/dsmd.pl" the service start fine.

**Comment by garnier-quentin** [comment]
Sorry but that's a rpm issue. Cannot fix it here.
