### ISSUE TITLE
Delete slots/services created if module is removed

### ISSUE THREAD

**Issue by centreon** [centreon/centreon-dsm#9]
---

Author Name: **Laurent Pinsivy** (Laurent Pinsivy)
Original Redmine Issue: 3457, https://forge.centreon.com/issues/3457
Original Date: 2012-07-23

---

Delete slots/services created by Centeron-DSM if module Centreon-DSM is removed from menu "Administration -> Modules"

**Comment by julienmathis** [comment]
no because we can't loose history.
